<?xml version="1.0"?>
<robot name="dog"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Defining the colors used in this robot -->
    <material name="Black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="White">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="Blue">
        <color rgba="0 0 1 1"/>
    </material>

    <material name="Red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- Constants -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- body_link properties -->
    <xacro:property name="body_link_height" value="0.08" />
    <xacro:property name="body_link_width" value="0.2" />
    <xacro:property name="body_link_length" value="0.4" />
    <xacro:property name="body_h" value="0.4" />

    <!-- leg_calf properties -->
    <xacro:property name="calf_height" value="0.025" />
    <xacro:property name="calf_width" value="0.025" />
    <xacro:property name="calf_len" value="0.2" />

    <!-- leg_thigh properties -->
    <xacro:property name="thigh_height" value="0.025" />
    <xacro:property name="thigh_width" value="0.025" />
    <xacro:property name="thigh_len" value="0.2" />

    <!-- leg_shoulder properties -->
    <xacro:property name="shoulder_radius" value="0.05" />
    <xacro:property name="shoulder_len" value="0.05" />

    <!-- point_feet properties -->
    <xacro:property name="point_feet_radius" value="0.017675" />

    <!-- Gripper frame -->
    <xacro:property name="grasp_frame_radius" value="0.001" />

    <!-- Inertial matrix -->
    <xacro:macro name="inertial_matrix" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="0.166667" ixy="0" ixz="0" iyy="0.166667" iyz="0" izz="0.166667"/>
        </inertial>
    </xacro:macro>

    <!-- base_link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_link_length/10} ${body_link_width/10} ${body_link_height/10}" />
            </geometry>
            <material name="White" />
        </visual>
        <!-- <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_link_length/10} ${body_link_width/10} ${body_link_height/10}" />
            </geometry>
        </collision> -->
    </link>

    <!-- body_link -->
    <link name="body_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_link_length} ${body_link_width} ${body_link_height}" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_link_length} ${body_link_width} ${body_link_height}" />
            </geometry>
        </collision>
        <xacro:inertial_matrix mass="5" />
    </link>

    <!-- leg -->
    <xacro:macro name="leg" params="leg_name">
        <link name="${leg_name}_calf_link">
            <visual>
                <origin xyz="0 ${calf_len/2} 0" rpy="0 0 0" />
                <geometry>
                    <box size="${calf_width} ${calf_len} ${calf_height}" />
                </geometry>
                <material name="White" />
            </visual>
            <collision>
                <origin xyz="0 ${calf_len/2} 0" rpy="0 0 0" />
                <geometry>
                    <box size="${calf_width} ${calf_len} ${calf_height}" />
                </geometry>
            </collision>
            <xacro:inertial_matrix mass="0.5" />
        </link>

        <link name="${leg_name}_thigh_link">
            <visual>
                <origin xyz="0 ${thigh_len/2} 0" rpy="0 0 0" />
                <geometry>
                    <box size="${thigh_width} ${thigh_len} ${thigh_height}" />
                </geometry>
                <material name="Blue" />
            </visual>
            <collision>
                <origin xyz="0 ${thigh_len/2} 0" rpy="0 0 0" />
                <geometry>
                    <box size="${thigh_width} ${thigh_len} ${thigh_height}" />
                </geometry>
            </collision>
            <xacro:inertial_matrix mass="0.5" />
        </link>

        <link name="${leg_name}_feet_link">
            <visual>
                <origin xyz="0 ${thigh_len/2} 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${point_feet_radius}" />
                </geometry>
                <material name="Black" />
            </visual>
            <collision>
                <origin xyz="0 ${thigh_len/2} 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${point_feet_radius}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="0.1"/>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
        </link>

        <joint name="${leg_name}_keen_joint" type="revolute">
            <origin xyz="0 ${calf_len} 0" rpy="0 0 1.57" />
            <parent link="${leg_name}_calf_link" />
            <child link="${leg_name}_thigh_link" />
            <axis xyz="0 0 1" />
            <limit effort="300.0" lower="-${M_PI}" upper="${M_PI}" velocity="1" />
            <dynamics damping="0" friction="0.1" />
        </joint>

        <joint name="${leg_name}_feet_joint" type="fixed">
            <origin xyz="0 ${thigh_len/2} 0" rpy="0 0 0" />
            <parent link="${leg_name}_thigh_link" />
            <child link="${leg_name}_feet_link" />
            <axis xyz="0 0 1" />
            <!-- <limit effort="300.0" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="1" /> -->
            <!-- <dynamics damping="0" friction="0.1" /> -->
        </joint>
    </xacro:macro>

    <!-- legs -->
    <xacro:leg leg_name="left_forward_leg" />
    <xacro:leg leg_name="left_back_leg" />
    <xacro:leg leg_name="right_forward_leg" />
    <xacro:leg leg_name="right_back_leg" />

    <!-- base_body_joint -->
    <joint name="base_body_joint" type="fixed">
        <origin xyz="0 0 0" rpy="3.14 0 0" />
        <parent link="base_link" />
        <child link="body_link" />
    </joint>

    <!-- leg_body_joint -->
    <joint name="left_forward_leg_body_joint" type="revolute">
        <origin xyz="${body_link_length/2} ${body_link_width/2+calf_height/2} 0" rpy="1.57 0.785 0" />
        <parent link="body_link" />
        <child link="left_forward_leg_calf_link" />
        <axis xyz="0 0 1" />
        <limit effort="300" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="1" />
        <dynamics damping="0" friction="0.1" />
    </joint>

    <joint name="left_back_leg_body_joint" type="revolute">
        <origin xyz="-${body_link_length/2} ${body_link_width/2+calf_height/2} 0" rpy="1.57 0.785 0" />
        <parent link="body_link" />
        <child link="left_back_leg_calf_link" />
        <axis xyz="0 0 1" />
        <limit effort="300" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="1" />
        <dynamics damping="0" friction="0.1" />
    </joint>

    <joint name="right_forward_leg_body_joint" type="revolute">
        <origin xyz="${body_link_length/2} -${body_link_width/2+calf_height/2} 0" rpy="1.57 0.785 0" />
        <parent link="body_link" />
        <child link="right_forward_leg_calf_link" />
        <axis xyz="0 0 1" />
        <limit effort="300" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="1" />
        <dynamics damping="0" friction="0.1" />
    </joint>

    <joint name="right_back_leg_body_joint" type="revolute">
        <origin xyz="-${body_link_length/2} -${body_link_width/2+calf_height/2} 0" rpy="1.57 0.785 0" />
        <parent link="body_link" />
        <child link="right_back_leg_calf_link" />
        <axis xyz="0 0 1" />
        <limit effort="300" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="1" />
        <dynamics damping="0" friction="0.1" />
    </joint>

    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/arm</robotNamespace>
        </plugin>
    </gazebo>

</robot>